### ISSUE TITLE
那有没有去壳工具呢

### ISSUE THREAD

**Issue by tghjnjvg** [WuFengXue/android-reverse#1]
那有没有去壳工具呢 大佬能不能再发一些安卓逆向教程基础

**Comment by WuFengXue** [comment]
新增了脱壳工具【FDex2】。

如果时间充裕的话，建议买本书来学习，非虫（个人看过他旧版的书，最近出了新版，但我还没看过）或者尼古拉斯的都很不错的。

如果有好的资源也欢迎提 PR ^_^

**Comment by tghjnjvg** [comment]
有没有在线版的呀

**Comment by WuFengXue** [comment]
项目下的[post.md](https://github.com/WuFengXue/android-reverse/blob/master/post.md)是我之前搜集的一些资源。

建议看看[吾爱](https://www.52pojie.cn)或者[看雪](https://bbs.pediy.com)的精华帖，会有最新的内容。
